config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'homes#top'
  resources :books
  root to: 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if
      @book.save
      redirect_to "/books/#{@book.id}", notice: 'Book was successfully created.'
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if
      @book.update(book_params)
      redirect_to "/books/#{@book.id}", notice:'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if
      @book.destroy
      redirect_to "/books", notice:'Book was successfully destroyed.'
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= form_with model:@book, local:true do |f| %>
  <div>
    <h4>Title</h4>
    <%= f.text_field :title %>
  </div>
  <div>
    <h4>Body</h4>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit 'Update Book' %>
  </div>
<% end %>
<div>
  <%= link_to "Show", "/books/#{@book.id}" %>
  <%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb
    <h1>Books</h1>
    <table>
      <div class="table-head">
        <div class="table-head-box">
          <div class="table-head-contents1">
            <h4>Title</h4>
          </div>
          <div class="table-head-contents2">
            <h4>Body</h4>
          </div>
          <div class="table-head-contents3"></div>
        </div>
      </div>
      <div class="table-body">
        <div class="table-body-box">
            <% @books.each do |book| %>
          <div class="table-body-contents1">
            <%= book.title %>
          </div>
          <div class="table-body-contents2">
            <%= book.body %>
          </div>
          <div class="table-body-contents3">
            <div class="show">
              <%= link_to "Show", book_path(book.id) %>
            </div>
            <div class="edit">
              <%= link_to "Edit", "/books/#{book.id}/edit" %>
            </div>
            <div class="destroy">
              <%=link_to "Destroy", "/books/#{book.id}", method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </table>
    <h2 class="form-title">New book</h2>
    <% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this book from being saved:
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>

    <%= form_with model:@book, local:true do |f| %>
        <div>
          <h4>Title</h4>
          <%= f.text_field :title %>
        </div>
        <div>
          <h4>Body</h4>
          <%= f.text_area :body %>
        </div>
        <div>
          <%= f.submit 'Create Book' %>
        </div>
    <% end %>

app/views/books/show.html.erb
<h2>Title</h2>
<p><%= @book.title %></p>
<h2>Body</h2>
<p><%= @book.body %></p>
<div>
  <%= link_to "Edit", "/books/#{@book.id}/edit" %>
  <%= link_to "Back", books_path %>
</div>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html lang="ja">

  <head>
    <title>Bookers</title>
  </head>

  <body>
    <h2>
      ようこそ
      <strong>Bookers</strong>
      へ！
      </h2>
    <p>
      <strong>Bookers</strong>
      では、さまざまな書籍に関するあなたの意見や
      <p>印象を共有し交換することができます</p>
    </p>
    <%= link_to "Start" ,"/books" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </body>
</html>